### ISSUE TITLE
sFlow input module

### ISSUE THREAD

**Issue by weyrick** [netboxlabs/pktvisor#106]
https://sflow.org/developers/specifications.php

reference https://github.com/bio-routing/flowhouse

https://github.com/sflow/host-sflow

https://github.com/sflow/sflowtool

https://github.com/cloudflare/goflow/tree/master/decoders

https://github.com/pavel-odintsov/fastnetmon/tree/master/src

**Comment by pmarciniakNS1** [comment]
A couple of thoughts about pktvisor<>sflow (and possibly other flow data formats like IPFIX, etc.):

- Watching a talk about https://github.com/bio-routing/flowhouse which among other things is augmenting sFlow data with routing information from BGP, I realised it would be interesting to augment sFlow with pktvisor data as well. This could allow us to get information like "give me top X queried names per source IP address", etc.

- Another idea that we discussed earlier is that pktvisor could output sFlow data itself. The reasoning here is that sFlow (and other flow data formats) are universally used by network engineers for network monitoring, so producing sFlow data should make it easy integrate pktvisor with existing network monitoring solutions.

- Furthermore pktvisor could also consume sFlow and combine it e.g. with its own DNS monitoring data for a more holistic view of the network traffic
