### ISSUE TITLE
dynamic policies per Top 10 IP

### ISSUE THREAD

**Issue by weyrick** [netboxlabs/pktvisor#107]
We want the ability to capture policies based on current top 10 IP addresses querying the server. This epic will represent the story.

**Comment by pmarciniakNS1** [comment]
- The idea behind this request is to get more granular insights about the traffic hitting a given server running pktvisor. The list of top talkers could be useful e.g. for traffic filtering in certain attack scenarios.
- That being said, in the future it would make sense to generate stats not only based on top 10 source IP addresses querying the server, but also based e.g. on the destination IP on the server. The reasoning here is that there may be multiple services listening on different IP addresses (and/or ports) on a single server. 
- I could imagine that once there is such a framework for capturing top talkers based on destination IP address, it could offer enough flexibility to configure and capture top talkers based on e.g. src/dst port/IP address pairs, etc. to meet each operator's needs.
