### ISSUE TITLE
How to connect with Grafana?

### ISSUE THREAD

**Issue by ToTheMax** [netboxlabs/pktvisor#11]
Hi guys! 
Could you provide some documentation how to connect this software with Grafana to get the WebUI?
I imported the dashboard json file but when I looked at the dashboard it says `Error updating options: Datasource named ES7-pktvisor3 was not found`

I'm not really familiar with Grafana but I guess I should add a Data Source?
Hope you can help me out!

-Max

**Comment by weyrick** [comment]
Hi @ToTheMax , yes, to use grafana you will have to first collect the output of pktvisor into a data source - this is not included in the project. One way to do it (and the way we do it at NS1) is to use telegraf generic HTTP input plugin to collect, and the elastic search output plugin to get it into the data source (in this case elasticsearch). If you do that, the included grafana dashboard should get you pretty close. 

Unfortunately we don't have better documentation on centralized collection yet, but there is an explanation with a few links in this talk on pktvisor: https://indico.dns-oarc.net/event/34/contributions/783/

**Comment by ToTheMax** [comment]
Okay I will have a look at that! Thanks a lot
