### ISSUE TITLE
Documentation for connecting with grafana

### ISSUE THREAD

**Issue by thatsk** [netboxlabs/pktvisor#15]
there is no instruction for connecting with existing grafana
like how to scrape the metric how to import the graphs

**Comment by thatsk** [comment]
Also, metrics should be compatible with  Prometheus datasource

**Comment by thatsk** [comment]
what is minimum grafana version should be used?

**Comment by thatsk** [comment]
what is minimum grafana version should be used? what is a port for exposing metrics information?

**Comment by weyrick** [comment]
Hello, indeed we need to improve documentation for central collection, it is on our list. You can find some information in this talk https://indico.dns-oarc.net/event/34/contributions/783/

pktvisord exposes JSON metrics on port 10853 by default. There is some API documentation available here: https://app.swaggerhub.com/apis/ns1labs/pktvisor/3.0.0-oas3

The best way to collect centrally is to scrape `/api/v1/metrics/bucket/1` once per minute, and send the results to your database of choice. It can be sent as-is to Elasticsearch, if you do that you can use the included grafana dashboard, which requires 7.2+

If you want to use Prometheus, currently you will have to convert the format. We have a beta version of a Prometheus scrapper, which we will release soon.

**Comment by weyrick** [comment]
Prometheus exporter will be in #19

**Comment by weyrick** [comment]
Please see #19 and #21 which both illustrate ways to collect. We will improve documentation further but I am closing this issue for now.
