### ISSUE TITLE
prometheus "name" label in top K metric should be unique per metric

### ISSUE THREAD

**Issue by weyrick** [netboxlabs/pktvisor#158]
Right now all TopK metrics render their prometheus output with a "name" label containing the frequent item:

```
dns_top_qname3{instance="gw",name=".fe.apple-dns.net"} 2
dns_top_qname3{instance="gw",name="clientservices.googleapis.com"} 2
dns_top_qname3{instance="gw",name="gs.apple.com"} 2
dns_top_qname3{instance="gw",name="cdn2.ghostery.com"} 2
dns_top_qtype{instance="gw",name="A"} 30
dns_top_qtype{instance="gw",name="HTTPS"} 8
dns_top_qtype{instance="gw",name="AAAA"} 2
```

This makes "name" very high cardinality, and also hampers data exploration and graphing in e.g. Grafana, which is unable the create an automatic filter on "name" because it is ambiguous which name should be filtered.

We should change this label to be specific per TopK metric, for example "qtype3" and "qtype" in the example above. This will shard the cardinality out, and give us a way to take advantage of Grafana "Filter by Value"
![Screen Shot 2021-12-09 at 1.19.39 PM.png](https://images.zenhubusercontent.com/619405487b3b8f4c04108cf3/957722f1-45b5-48d8-9c84-f25feebd9507)

HOWEVER this is a **breaking change** and will break existing dashboards that already use "name" so we need to handle that appropriately.

**Comment by weyrick** [comment]
let's talk about how to feature flag this

**Comment by ghost** [comment]
This task changes the aggregated qname dns to lower case. This changes the qname cardinality as well.

**Comment by dscabral** [comment]
```
{[{__name__ packets} {instance agent} {agent_id 3f730500-0602-44f3-919a-388a05ffc25f} {agent agent} {policy_id c361089c-28ba-43dc-9b70-4758f1898f92} {policy policy} {TopIpv6 ff02::fb}] {2022-01-25 10:17:58.916091591 -0300 -03 m=+231.494543931 5}} 
{[{__name__ packets} {instance agent} {agent_id 3f730500-0602-44f3-919a-388a05ffc25f} {agent agent} {policy_id c361089c-28ba-43dc-9b70-4758f1898f92} {policy policy} {TopIpv6 ff02::16}] {2022-01-25 10:17:58.916135703 -0300 -03 m=+231.494588043 2}}
```

**Comment by dscabral** [comment]
@weyrick is this the expected format?

**Comment by manrodrigues** [comment]
![image](https://user-images.githubusercontent.com/78241475/151847472-4d7fbe49-1c37-4204-892a-eeb780ac40f8.png)
