### ISSUE TITLE
Write Unit tests for Metrics Module

### ISSUE THREAD

**Issue by iatdaitan** [netboxlabs/pktvisor#160]
Expand unit tests coverage at `src/tests/test_metrics.cpp` to cover functionality found in `src/Metrics.cpp/h` and `AbstractMetricsManager.h`

**Comment by ghost** [comment]
Before
![old.png](https://images.zenhubusercontent.com/61ae58f152484b833b0aa7e0/cd5a3001-3a1b-4e7b-a261-23110a222e7f)
Then
![current_Metrics_coverage.png](https://images.zenhubusercontent.com/61ae58f152484b833b0aa7e0/04c76607-88ca-4477-a9fe-1bc43a1d9e80)

**Comment by ghost** [comment]
for abstract.
before
![old_abstract.png](https://images.zenhubusercontent.com/61ae58f152484b833b0aa7e0/6b6e628f-96bf-4684-b6de-5fb46180569d)
then:
![then_abstract.png](https://images.zenhubusercontent.com/61ae58f152484b833b0aa7e0/7a29347e-3b79-4a53-8a96-93c4a68564f2)
