### ISSUE TITLE
improve dnstap module

### ISSUE THREAD

**Issue by weyrick** [netboxlabs/pktvisor#163]
- [ ] i/o timeout disconnects idle clients
- [ ] optionally limit max number of clients
- [ ] handle FINISH control frame appropriately in bi directional
- [ ] extract more/better data in Net/DNS modules
- [ ] ring buffer in frame session
- [ ] unit test covering case of frame parse waiting for more data

**Comment by ghost** [comment]
` i/o timeout disconnects idle clients`: should we use tcp keepAlive feature for that?
