### ISSUE TITLE
Agents: when multiple containers are running just using UI command (without specify port) agent logs displays errors related with policies not linked with the agent

### ISSUE THREAD

**Issue by manrodrigues** [netboxlabs/pktvisor#171]
Create new agent (agent 1)
Provision agent container
Create new agent groups with same tag as agent 1
Create new policy
Create new dataset using existing group and sink, but newly policy
Create new agent (agent 2)
Provision agent container
Create new policy
Create new dataset using existing group (referred to agent 2) and sink, but newly policy
Expected results:
Policy should be applied to the agent and metrics should keeping be scrapped
Current  result:
Policy is applied
Container logs starts to display error “policy name not found” referred to policy applied on other agent (note that policy-to-apply is not linked with agent 1, just with agent 2. Same error will appear on agents 2 logs: policies referred to agent 1 will trigger an error)

<br>

{"level":"info","ts":1640793378.5644362,"caller":"policyMgr/manager.go:146","msg":"policy applied successfully","policy_id":"efad38b2-8871-41c4-b709-3b4e64f9a75d", "policy_name":"policy-2-cont"}
{"level":"error","ts":1640793395.1898673,"caller":"pktvisor/pktvisor.go:279","msg":"skipping pktvisor policy not managed by orb","policy":"policy-to-apply","error":"policy name not found","stacktrace":"github.com/ns1labs/orb/agent/backend/pktvisor.(*pktvisorBackend).Start.func2\n\t/go/src/github.com/ns1labs/orb/agent/backend/pktvisor/pktvisor.go:279\nreflect.Value.call\n\t/usr/lib/go-1.15/src/reflect/value.go:476\nreflect.Value.Call\n\t/usr/lib/go-1.15/src/reflect/value.go:337\ngithub.com/go-co-op/gocron.callJobFuncWithParams\n\t/root/go/pkg/mod/github.com/go-co-op/gocron@v1.9.0/gocron.go:78\ngithub.com/go-co-op/gocron.(*executor).start.func1.1\n\t/root/go/pkg/mod/github.com/go-co-op/gocron@v1.9.0/executor.go:90\ngolang.org/x/sync/singleflight.(*Group).doCall.func2\n\t/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:193\ngolang.org/x/sync/singleflight.(*Group).doCall\n\t/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:195\ngolang.org/x/sync/singleflight.(*Group).Do\n\t/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:108\ngithub.com/go-co-op/gocron.(*executor).start.func1\n\t/root/go/pkg/mod/github.com/go-co-op/gocron@v1.9.0/executor.go:82"}

**Comment by ghost** [comment]
I think that SO_REUSEPORT is linux kernel enabled flag:
[https://programmer.group/the-evolution-of-reuseport-in-the-linux-kernel.html](https://programmer.group/the-evolution-of-reuseport-in-the-linux-kernel.html)
Probably we will need to add httpcpp header to our code and change it. what your thoughts @weyrick ?

**Comment by weyrick** [comment]
I was thinking we could just `#undef SO_REUSEPORT` before the `#include <httplib.h>` in HttpServer.h

**Comment by manrodrigues** [comment]
Not able to run multiple containers using same port

Steps
- provision an agent container
- create and try to provide another agent container

Expected result:
- second container must fail (exit) and agent status should remains as "new"

![image](https://user-images.githubusercontent.com/78241475/150145538-8a4ef2ed-df69-4034-8dd6-61a247217b6f.png)


![image](https://user-images.githubusercontent.com/78241475/150145345-89773f28-9024-47be-b17b-406a6b2e4082.png)

![image](https://user-images.githubusercontent.com/78241475/150146287-4c695af9-4028-4bf9-96b3-22fa7471ddb2.png)

**Comment by manrodrigues** [comment]
using different ports through `ORB_BACKENDS_PKTVISOR_API_PORT` env var, second container is up 

![image](https://user-images.githubusercontent.com/78241475/150147349-77601236-5c45-47c2-ba68-7250dbbedeb7.png)
