### ISSUE TITLE
pktvisord: High memory usage

### ISSUE THREAD

**Issue by iatdaitan** [netboxlabs/pktvisor#226]
High memory usage during packet capture

**Comment by ghost** [comment]
Tested with pktvisor-reader over huge traffic pcap files. The issues seems to be related to pktvisor PCAP TCP processing.
more specific in the `auto result = _tcp_reassembly.reassemblePacket(packet);` call.

For huge traffic `ConnectionInfoList` does not stops growing.

**Comment by ghost** [comment]
removed callbacks from `_tcp_reassembly` and also commented their logic to not process anything inside the callbacks and the memory still grows.

**Comment by ghost** [comment]
We validated that memory increase is due to TCP reassembly logic. If there is no FIN or RST packet, connection vector keeps growing.
