### ISSUE TITLE
HTTP response status code for policies and taps creation must be 201

### ISSUE THREAD

**Issue by manrodrigues** [netboxlabs/pktvisor#246]
Pktvisor current response status code for policies and taps creation is 200, but must be 201

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/5d5e3112-4efa-43a3-ae30-e4dc4487e6b4)

![image](https://user-images.githubusercontent.com/78241475/186220478-463abe42-eabf-45cb-88de-2604c6277b38.png)

**Comment by leoparente** [comment]
This would require changes on orb agent as well:
https://github.com/ns1labs/orb/blob/88f2d24fc320924972f7c68bdab1835a22cd1c53/agent/backend/pktvisor/pktvisor.go#L120
