### ISSUE TITLE
HTTP response status code for policies and taps removal must be 204

### ISSUE THREAD

**Issue by manrodrigues** [netboxlabs/pktvisor#247]
Once there is no message or information on response, status code expected for policy and taps removal is 204, but currently pktvisor return 200. <br><br>

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/bce9a237-e747-480f-8e93-fd6b5f001279)

![image](https://user-images.githubusercontent.com/78241475/186220948-57eac91c-cfc4-4c76-85f4-a123ffc549b0.png)

PS:
I'm based on it:
![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/bd7adafb-0226-4e50-88f8-e736a71be3cd)

**Comment by leoparente** [comment]
it would require changes on orb as well:
https://github.com/ns1labs/orb/blob/88f2d24fc320924972f7c68bdab1835a22cd1c53/agent/backend/pktvisor/pktvisor.go#L120
