### ISSUE TITLE
Top 10 metrics: Make "10" a configurable parameter

### ISSUE THREAD

**Issue by rboucher-me** [netboxlabs/pktvisor#300]
Ideally this would be configurable at the individual Top 10 metric, but an initial implementation could be limited to setting the value at the module level in the policies (i.e. per named handler)

**Comment by leoparente** [comment]
@rboucher-ns1 i did it per policy at same level of` deep sample` and `periods` should it be at each handler level?
@weyrick what are your thoughts?
