### ISSUE TITLE
DNS Handler - Create DnsHandler V2

### ISSUE THREAD

**Issue by rboucher-me** [netboxlabs/pktvisor#341]
The DNS handler should still be able to provide `xact` metrics when an `rcode` filter is applied.

Currently, if a filter is applied such as `"only_rcode": 3` (only NXDOMAIN), the `xact` metrics are empty (all zeroes).

![Image 2022-07-18 at 11.45.10 AM.jpg](https://images.zenhubusercontent.com/6275686817eae782dc76eac9/3e8a4bb9-5a32-4a2e-b7e7-06ceb594e139)

**Comment by leoparente** [comment]
https://github.com/ns1labs/orb/wiki/DNS-v2
