### ISSUE TITLE
Reduce dns port cardinality

### ISSUE THREAD

**Issue by weyrick** [netboxlabs/pktvisor#382]
The DNS handler contains a `top_udp_ports` metric, enabled by default, which is a top 10 DNS client ports table, intended to help identify certain traffic abuses (for example, a flood all coming from the same client source port). However, when there is no malicious traffic, the label is very high cardinality because this field in DNS is intentionally random. Analysis shows this cardinality can account for >40% of total metric series.

We can greatly reduced cardinality here by introducing a threshold to be included in the table output - for example, only include ports that have received more than 120 queries in a time bucket (a number we've researched from empirical data). we can also make this number configurable via handler config. This allows abuses to still be understood while minimizing the number of active time series.

**Comment by rboucher-me** [comment]
Another approach to consider is using a threshold based on the number of DNS queries (`dns_wire_packets_queries`). This would scale the threshold as a function of the amount of DNS traffic observed.

Only keep a UDP port in `top_udp_ports` if query_count(port) / `dns_wire_packets_queries` > %threshold (configurable, but default might be something like 1%)

We probably also want a low "static" threshold for the low volume cases, something like a minimum 1 event/s (60 occurrences within any 1-minute window)

**Comment by weyrick** [comment]
i think the TopN class in Metrics.h can get a new configurable member variable for percentile threshold. in the to_json and to_prometheus methods, when it's getting the top N, we add new functionality to first put the top N values through a quantile sketch - should be very fast. we can then get the value of the Nth percentile we're configured for, and when looping through the top N we know exactly where to cut the list
