### ISSUE TITLE
Expose the interface observed when "auto" is chosen as iface

### ISSUE THREAD

**Issue by manrodrigues** [netboxlabs/pktvisor#436]
@manrodrigues commented on [Fri Sep 09 2022](https://github.com/ns1labs/ns1-pktvisor/issues/37)

When "auto" is chosen as iface, pktvisor binds on the most used interface, but there is no way to the user knows which iface is being observed and as a user I want to know it.

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/d590516e-f3d1-4405-a48a-d183e9a335ff)

**Comment by leoparente** [comment]
This is only possible to perform for InputStream data and not for TAP. the most used interface can change during time and Tap should not change over time, but InputStream which can change over a gent reboot can display this info properly:
![Screenshot from 2022-09-24 14-23-59](https://user-images.githubusercontent.com/23251360/192113127-d50490a1-bcdf-4439-b887-4f6dd4b5fb47.png)

So, this enhancement was performed for 'Input' information and not for tap on PR #471
