### ISSUE TITLE
I had a connection problem some time after I started using pktvisor in Docker.

### ISSUE THREAD

**Issue by QueryVS** [netboxlabs/pktvisor#463]
I was using pktvisor on docker. My connection interface stopped and not working. 
I tried everything and finally thought of stopping pktvisor, stopped it and rebooted the system.
Problem solved.
There was no problem before. I did not understand why it was caused.
I was testing what kind of tool it is, I wasn't working on the server, but running this tool on the server can be dangerous.

Operating system : Gentoo OpenRC
kernel : 5.17.1
network : net-misc/netifrc-0.7.3

Docker version 20.10.0-dev
image : latest (Sep 21 2022)

**Comment by weyrick** [comment]
Hi @QueryVS, sorry you had trouble. Can you explain your setup more? Exactly which pktvisor docker image were you using, with which command line (and/or config file) was it run with? What is the output of `pktvisord --version`?

In general, pktvisor uses the same packet capture mechanism as "tcpdump" (libpcap) so it should not be any more dangerous than that is. Rest assured pktvisor is running on lots of critical production infrastructure without this problem.
