### ISSUE TITLE
native Windows binary

### ISSUE THREAD

**Issue by weyrick** [netboxlabs/pktvisor#51]
There is interest in a native Windows version of a binary because docker on windows does not support host networking. Investigate feasibility

**Comment by leoparente** [comment]
Pktvisor is building on Windows! I will create a ticket for improvements
![image](https://user-images.githubusercontent.com/23251360/198288283-b281118b-3782-4345-ace7-bd98de1b73e0.png)

**Comment by leoparente** [comment]
https://github.com/ns1labs/pktvisor/issues/512
