### ISSUE TITLE
OpenMetrics support in pktvisor

### ISSUE THREAD

**Issue by rboucher-me** [netboxlabs/pktvisor#515]
This is a research spike to understand whether supporting [OpenMetrics](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md) in pktvisor makes sense or not, and what would be involved in terms of steps and efforts to achieve this.

**Comment by leoparente** [comment]
Pktvisor prometheus is pretty compliant to OpenMetrics. But it would require some changes:

- [ ] add `#EOF` at the end of the response request
- [ ] all snake case metrics name: should rename `geoLoc` metrics to be compliant
- [ ] MetricsFamily (#HELP, #TYPE comments) MUST be unique for a MetricSet (response request). 
       However if we have more than one equal handler, we repeat the metrics Family
