### ISSUE TITLE
Spike - Histogram support in pktvisor

### ISSUE THREAD

**Issue by rboucher-me** [netboxlabs/pktvisor#516]
This is a research spike to understand the effort needed to support Prometheus-style histograms in pktvisor (https://prometheus.io/docs/concepts/metric_types/#histogram).

This effort would be a preliminary step to supporting OpenTelemetry exponential histograms(https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#exponential-bucket-histogram-aggregation)

**Comment by weyrick** [comment]
Let's see if apache data sketches we are using has what we need here https://datasketches.apache.org/docs/Quantiles/SketchingQuantilesAndRanksTutorial.html

**Comment by weyrick** [comment]
Also check https://github.com/open-telemetry/opentelemetry-cpp

**Comment by leoparente** [comment]
exponential histogram
