### ISSUE TITLE
support more rcodes in DNS only_rcode filter

### ISSUE THREAD

**Issue by weyrick** [netboxlabs/pktvisor#563]
Currently we support only a handful; add all defined rcodes.

https://github.com/ns1labs/pktvisor/blob/db7b32d1f400273f44a222768d89e622ae5f4fd8/src/handlers/dns/v1/DnsStreamHandler.cpp#L70

**Comment by tbernstein** [comment]
This will be helpful to investigate the source of unexpected rcodes.
