### ISSUE TITLE
netprobe_response_histogram_us_bucket is always returning the maximum value (instead of the correct one)

### ISSUE THREAD

**Issue by manrodrigues** [netboxlabs/pktvisor#572]
Values ​​returned for the metric `netprobe_response_histogram_us_bucket`  are not correct. Instead of returning the correct value, the maximum value is being returned (interesting note: for some specific points the value seems correct. Some inconsistency perhaps?)

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/55777c2b-c275-45e6-aaff-24e68f934ec1)

Some data:

[https://app.zenhub.com/files/241899022/fbddaab9-c450-42d1-8ab3-68d1bb6d69ab/download](https://app.zenhub.com/files/241899022/fbddaab9-c450-42d1-8ab3-68d1bb6d69ab/download)

**Comment by manrodrigues** [comment]
Agent version: `0.22.0-develop-fdcf251`
pktvisor version: `4.3.0-develop-288fd71`

![image](https://user-images.githubusercontent.com/78241475/211320888-ce8919d7-aee7-4a09-acdc-99eacc85ad3f.png)

**Comment by leoparente** [comment]
@manrodrigues  please, retest it with End to End OTLP
