### ISSUE TITLE
Netprobe should support atomic operations on test targets

### ISSUE THREAD

**Issue by rboucher-me** [netboxlabs/pktvisor#578]
As a network automation engineer,
I would like the ability to create, read, modify and delete individual test instances using an API,
So that I can build automations with atomic operations without needing to concurrently manage or know about other existing test instances.

Currently, netprobe test targets are defined as a blob/list in the `input` section of a policy and require the whole list to be provided for every modification to the list.

The target solution would provide API endpoints that allow create, read, modify and delete operations on individual test target instances.

**Comment by leoparente** [comment]
This must be achieved by the tool/app that uses pktvisor policies
