### ISSUE TITLE
IP summarization based on subnet CIDR

### ISSUE THREAD

**Issue by rboucher-me** [netboxlabs/pktvisor#583]
As a network traffic engineer,
I would like to be able to easily and succinctly configure how to summarize flow traffic by IP using subnet CIDRs,
So that I can more easily observe network traffic trends, reduce the volume of data I need to collect and improve the responsiveness of my observability tools.

This feature would allow defining IP summarization by subnets using broad rules without having to explicitly identify all subnets that should be summarized.

The target solution would support configuring IP summarization with a configuration such as:
```
summarize_ips_by_cidr: true
cidr_summarization:
        - 1-10.0.0.0/8
        - 172.16-31.0.0/16 
	- 0.0.0.0/24      # wildcard meaning all other IPs should be summarized as /24 (e.g. "a.b.c.0")
exclude_ips_from_summarization:
	- 10.1.0.0/16     # exclude all IPs in this subnet from summarization
	- 192.168.1-255.0/24
```

**Comment by leoparente** [comment]
`exclude_ips_from_summarization`: I think it does not make sense to change that... It would add more complexity and the same could be achieved with netmasks
