### ISSUE TITLE
[PKT-3] Add IP summarization exclusion based on ASN

### ISSUE THREAD

**Issue by rboucher-me** [netboxlabs/pktvisor#589]
The IP summarization configuration parameter of the Flow handler currently supports exclusions based on a list of subnets. It would be useful in certain settings to be able to define this exclusion based on the ASN number as well. Something like:

```
summarize_ips_by_asn: true
exclude_asns_from_summarization:
    - 62597
```

<sub>[PKT-3](https://linear.app/netboxlabs/issue/PKT-3/add-ip-summarization-exclusion-based-on-asn)</sub>

**Comment by leoparente** [comment]
@rboucher-me
