### ISSUE TITLE
AppImage does not work on Alpine linux

### ISSUE THREAD

**Issue by weyrick** [netboxlabs/pktvisor#88]
```
Hi Shannon, On Alpine linux (musl c) :
ldd ./pktvisor-x86_64-3.2.0.AppImage 
	/lib64/ld-linux-x86-64.so.2 (0x7f01ebc40000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f01ebc40000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f01ebc40000)
	libz.so.1 => /lib/libz.so.1 (0x7f01ebc26000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f01ebc40000)
Error relocating ./pktvisor-x86_64-3.2.0.AppImage: gnu_dev_makedev: symbol not found
```

This appears to be related to https://github.com/AppImage/AppImageKit/issues/1015

**Comment by weyrick** [comment]
Note that on e.g. Ubuntu:
```
ldd ./pktvisor-x86_64.AppImage
	not a dynamic executable
```

**Comment by probonopd** [comment]
glibc needs to be installed on Alpine Linux for AppImages to run.
At least until we can get them to work using https://git.adelielinux.org/adelie/gcompat/; it seems like https://github.com/AppImage/AppImageKit/pull/1168 can be the key to this.

**Comment by probonopd** [comment]
With the [static runtime](https://github.com/AppImage/AppImageKit/issues/877), glibc no longer needs to be installed on Alpine Linux to run an AppImage (if what is inside the AppImage is either bundling _everything_, or is statically linked, or consists of platform-independent interpreted code/scripts).

**Comment by weyrick** [comment]
We've moved away from AppImage and now have static binaries.

**Comment by probonopd** [comment]
Just saying, if you put a static binary into an AppImage with the static runtime, then it can run on Alpine and other Linux distributions. (Why would one want to do such a thing? Maybe to bundle icons, translations, etc. alongside the application.)

**Comment by weyrick** [comment]
Understood, thanks!
