### ISSUE TITLE
implement RFC #77 (module reflection)

### ISSUE THREAD

**Issue by weyrick** [netboxlabs/pktvisor#90]
see #77

**Comment by rboucher-me** [comment]
The RFC needs to be revisited and updated.

**Comment by leoparente** [comment]
C++ does not support reflection by standard. It still a [proposal](https://meetingcpp.com/blog/items/reflections-on-the-reflection-proposals.html). We should discuss the better way to achieve that RFC.

Some C++ reference libs:
[Boost.PFR](https://www.boost.org/doc/libs/1_75_0/doc/html/boost_pfr.html)
[Cereal](https://github.com/USCiLab/cereal)
[refl-cpp](https://github.com/veselink1/refl-cpp)

**Comment by weyrick** [comment]
yes to be clear this is not C++ code level "reflection", it's just a way for pktvisor to self-describe and document the handler capabilities, configuration, metrics, metric groups, etc.
